name: WebGL Example
on:
  release:
    types:
    - published

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
        persist-credentials: false

    # Cache
    - uses: actions/cache@v1.1.0
      with:
        path: Library
        key: Library

    # Build
    - name: Build project
      uses: webbertakken/unity-builder@v1.2
      with:
        unityVersion: 2021.3.5f1
        targetPlatform: WebGL

    # Output
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build/WebGL/WebGL # The folder the action should deploy.
        TARGET_FOLDER: play
        CLEAN: true